apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-recursor
  labels:
    k8s-app: pdns-recursor
spec:
  replicas: 4
  selector:
    matchLabels:
      k8s-app: pdns-recursor
  template:
    metadata:
      annotations:
        fluentd.packet.net/efk: stdout+stderr
        fluentd.packet.net/efk-index: pdnsrecursor
      labels:
        k8s-app: pdns-recursor
    spec:
      containers:
        - name: pdns-recursor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
          env:
          - name: PDNS_LOCAL_ADDRESS
            value: 0.0.0.0
            # TODO: Add a livenessProbe and readinessProbe
            # livenessProbe:
            #   httpGet:
            #     path: /
            #     port: http
            # readinessProbe:
            #   httpGet:
            #     path: /
            #     port: http
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 1
              memory: 512Mi
      imagePullSecrets:
        - name: {{ .Values.secret.name }}
