apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJhMlYzWVc1bk9rdG5jbmgwTDNwNFFtZ3ZWQzlNZFRsSWMweG5TME4wTlVsMWFEQmFabFZWVDFwQ1pqWkdVbUU0UTNSRVlVOHJiVUZ0TlhONlZ6ZFdZa053UTFkS1ZXYz0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
