apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: hegel
#    metallb.universe.tf/allow-shared-ip: hegel
  name: hegel
  labels:
    k8s-app: hegel
spec:
  externalTrafficPolicy: Local
  selector:
    k8s-app: hegel
  type: LoadBalancer
  ports:
  - name: grpc
    port: 50060
    protocol: TCP
    targetPort: grpc
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    k8s-app: hegel
