apiVersion: apps/v1
kind: Deployment
metadata:
  name: tink-cli
  labels:
    k8s-app: tink-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: tink-cli
  template:
    metadata:
      annotations:
        fluentd.packet.net/efk: stdout+stderr
        fluentd.packet.net/efk-index: tink-cli
      labels:
        k8s-app: tink-cli
    spec:
      containers:
        - name: tink-cli
          image: "quay.io/tinkerbell/tink-cli-pr:metadata-hw"
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: tink-cli-env
#          livenessProbe:
#            httpGet:
#              path: /_packet/healthcheck
#              port: http
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
