apiVersion: v1
kind: Secret
metadata:
  name: tink-cli-env
  labels:
    k8s-app: tink-cli
type: Opaque
data:
{{- range $key, $value := .Values.tink_cli.env }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
