apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: worker1
spec:
  terminationGracePeriodSeconds: 30
  domain:
    cpu:
      cores: 2
    clock:
      utc: {}
      timer:
        hpet:
          present: false
        pit:
          tickPolicy: delay
        rtc:
          tickPolicy: catchup
    resources:
      requests:
        memory: 4096M
    devices:
      rng: {}
      #autoattachGraphicsDevice: false
      disks:
      - name: emptydisk
        disk:
          bus: virtio
        bootOrder: 1
      interfaces:
      # - name: default
      #   masquerade: {}
      - name: tink-dev
        bridge: {}
        macAddress: "08:00:27:00:00:01"
        bootOrder: 2
  networks:
  # - pod: {}
  #   name: default
  - multus:
      networkName: tink-dev-no-ip
    name: tink-dev
  volumes:
  - name: emptydisk
    emptyDisk:
      capacity: "10Gi"
