image:
  repository: quay.io/packet/pdns-recursor
  tag: 194-252a9cda4d99a837ae643fc974d81889b48838e6
  pullPolicy: IfNotPresent

clusterFQDN: ''
clusterShortName: ''
env: ''
location: ''
packetAPI: ''
kubeApiEndpoint: ''
poolReady: ''

pdns:
  pool: pdns-recursor
  services:
    - ip: "172.23.17.135"
      protocol: UDP
      port: 53
      targetPort: dns-udp
    - ip: "172.23.17.135"
      protocol: TCP
      port: 53
      targetPort: dns-tcp
secret:
  name: kwang-pull-secret 
