apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    k8s-app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nginx
  template:
    metadata:
      labels:
        k8s-app: nginx
    spec:
      nodeName: sv16-ems-sitectl-node02
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 80
            name: nginx
            protocol: TCP
          volumeMounts:
          - name: nginx-images
            mountPath: /usr/share/nginx/html/
          - name: tink-tls-keys
            readOnly: true
            mountPath: /certs/
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - cp /certs/ca.pem /usr/share/nginx/html/workflow/ca.pem
      volumes:
      - name: nginx-images
        hostPath:
          path: /data
          type: Directory
      - name: tink-tls-keys
        secret:
          secretName: tink-tls-keys
