apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
#    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    k8s-app: nginx
  name: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: "nginx.{{ .Values.location }}.{{ .Values.clusterFQDN }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
