apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: nginx
#    metallb.universe.tf/allow-shared-ip: nginx
  name: nginx
  labels:
    k8s-app: nginx
spec:
  externalTrafficPolicy: Local
  selector:
    k8s-app: nginx
  type: LoadBalancer 
  ports:
    - name: nginx
      port: 80
      targetPort: 80
      protocol: TCP
