kind: Service
apiVersion: v1
metadata:
  annotations:
    metallb.universe.tf/address-pool: boots-dhcp
    metallb.universe.tf/allow-shared-ip: boots-dhcp
  labels:
    k8s-app: boots
  name: boots-udp
spec:
  externalTrafficPolicy: Local
  selector:
    k8s-app: boots
  type: LoadBalancer
  ports:
  - name: tftp
    port: 69
    protocol: UDP
    targetPort: tftp
  - name: syslog
    port: 514
    protocol: UDP
    targetPort: syslog
