apiVersion: v2
name: tink-cli
description: A Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: v1
sources:
  - https://github.com/packethost/tink
maintainers:
  - name: nobody
    email: someone@packet.com

