apiVersion: v1
kind: Service
metadata:
  name: pbnj
  labels:
    k8s-app: pbnj
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    k8s-app: pbnj
