apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: pbnj-auth
  labels:
    k8s-app: pbnj
spec:
  backendType: systemManager
  data:
    - key: /{{ .Values.env }}/{{ .Values.location }}/pbnj/access-id
      name: access-id
    - key: /{{ .Values.env }}/{{ .Values.location }}/pbnj/access-secret
      name: access-secret
