---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    k8s-app: tink
  name: tink-http
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx-external
  rules:
  - host: tink-cert.{{ .Values.clusterFQDN }}
    http:
      paths:
      - backend:
          serviceName: tink
          servicePort: tink-cert
        path: /cert
      - backend:
          serviceName: tink
          servicePort: tink-cert
        path: /metrics
  tls:
  - hosts:
    - tink-cert.{{ .Values.clusterFQDN }}
    secretName: tink-cert.{{ .Values.clusterFQDN }}
