apiVersion: v1
kind: Service
metadata:
  name: tink
  labels:
    k8s-app: tink
spec:
  selector:
    k8s-app: tink
  type: ClusterIP
  ports:
  - name: tink-grpc
    port: 42113
    protocol: TCP
    targetPort: tink-grpc
  - name: tink-cert
    port: 42114
    protocol: TCP
    targetPort: tink-cert
  selector:
    k8s-app: tink
